

export const FORMULARIO_PROYECTO = 'PROYECTO_PROYECTO'; 
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO'; 
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO'; 
export const ERROR_FORMULARIO_PROYECTO = 'ERROR_FORMULARIO_PROYECTO'; 
export const PROYECTO_SELECCIONADO = 'PROYECTO_SELECCIONADO'; 
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'; 

export const FILTRAR_TAREA = 'FILTRAR_TAREA'; 
export const AGREGAR_TAREA = 'AGREGAR_TAREA'; 
export const ERROR_FORMULARIO_TAREA = 'ERROR_FORMULARIO_TAREA'; 
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA'; 
export const ACTUALIZAR_ESTADO = 'ELIMINAR_TAREA'; 
export const SELECCIONAR_TAREA = 'SELECCIONAR_TAREA'; 
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA'; 

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'; 
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'; 

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'; 
export const REGISTRO_ERROR = 'REGISTRO_ERROR'; 
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS'; 
export const LOGIN_EXITOSO = 'LOGIN_ERROR'
export const LOGIN_ERROR = 'LOGIN_ERROR'; 
export const CERRAR_SESION = 'LOGIN_ERROR'; 